version: '3.8'

services:
  my-burger-order-service:
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      PAYMENT_SERVICE_URL: ${MP_PAYMENT_URL}
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      JWT_KEY: ${JWT_KEY}
      MP_REQUEST_URL: ${MP_REQUEST_URL}
      MP_AUTH_TOKEN: ${MP_AUTH_TOKEN}
      LOG_LEVEL: "DEBUG"
  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  wiremock:
    platform: linux/amd64
    image: holomekc/wiremock-gui:3.5.7-alpine
    ports:
      - "9090:8080"
    volumes:
      - ./mappings:/home/wiremock/mappings
    entrypoint: ["/docker-entrypoint.sh", "--global-response-templating", "--disable-gzip", "--verbose"]

volumes:
  data:

networks:
  my-burger:
    driver: bridge
