server:
  forward-headers-strategy: framework
  port: ${MYBURGUER_SERVER_PORT:8080}
  shutdown: graceful
  servlet:
    context-path: /api/v1

management:
  server:
    port: ${MYBURGUER_SERVER_PORT:8080}
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

spring:
  application.name: myburguercontrol
  config:
    import: optional:file:.env[.properties]
  data:
    mongodb:
      database: my-burger
      uuid-representation: standard
      username: ${MONGODB_USERNAME}
      password: ${MONGODB_PASSWORD}
      uri: ${MONGODB_URI}
      collection:
        orders: orders
        customers: customers

  jackson:
    default-property-inclusion: non_null
    deserialization:
      fail_on_unknown_properties: false
    serialization:
      fail_on_empty_beans: false
      write_dates_as_timestamps: false
    property-naming-strategy: SNAKE_CASE

third-party:
  payment-integration:
    url: ${PAYMENT_SERVICE_URL}
    connectionTimeout: 5000
    readTimeout: 5000

springdoc:
  version: '@springdoc.version@'
  swagger-ui:
    use-root-path: true
    tagsSorter: alpha
    operationsSorter: alpha
    writer-with-order-by-keys: true
  show-actuator: false
  path: /swagger-ui/index.html

logging:
  level:
    org.springframework.web: ${LOG_LEVEL:DEBUG}
    io.github.soat7.myburguercontrol: ${LOG_LEVEL:DEBUG}
