name: CI [MyBurguer - Order Service]

on: [push, pull_request]

env:
  REPO_NAME: ${{ github.event.repository.name }}
  
jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout sources
      uses: actions/checkout@v4

    - name: Set title
      run: echo "TITLE_STEP=[MyBurguer - Order Service]" >> $GITHUB_ENV
      
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 21
        cache: 'gradle'
        
    - name: Setup Gradle ${{ env.TITLE_STEP }}
      uses: gradle/actions/setup-gradle@v3
      with:
        build-scan-publish: true
        build-scan-terms-of-use-url: "https://gradle.com/terms-of-service"
        build-scan-terms-of-use-agree: "yes"

    - name: Run build ${{ env.TITLE_STEP }}
      run: ./gradlew clean build --no-daemon -x test
        
    - name: Run tests ${{ env.TITLE_STEP }}
      run: ./gradlew test --info --stacktrace

    - name: Generate JaCoCo Test Coverage Report ${{ env.TITLE_STEP }}
      run: ./gradlew jacocoTestReport

    - name: Get current date ${{ env.TITLE_STEP }}
      id: date
      run: echo "::set-output name=date::$(date +'%Y%m%d')"

    - name: Check Test Coverage ${{ env.TITLE_STEP }}
      run: |
        echo "Test Coverage Report:"
        cat build/reports/jacoco/test/html/index.html
        ls -la build/reports/jacoco/test/

    - name: Upload JaCoCo Test Coverage Report to Artifacts ${{ env.TITLE_STEP }}
      uses: actions/upload-artifact@v4
      with:
        name: jacoco-report
        path: build/reports/jacoco/test/html/

    - name: Create Coverage Badges
      uses: jaywcjlove/coverage-badges-cli@v2.1.0
      with:
        source: build/reports/jacoco/test/json/test-json-summary.json

    - name: Authentication Docker Hub ${{ env.TITLE_STEP }}
      uses: docker/login-action@v3.2.0
      with:
        username: ${{secrets.DOCKERHUB_USER}}
        password: ${{secrets.DOCKERHUB_PWD}}

    - name: Build the Docker image ${{ env.TITLE_STEP }}
      uses: docker/build-push-action@v6.0.0
      with:
        context: ./
        file: ./Dockerfile
        push: true
        tags: |
          fiapmyburguer/${{ env.REPO_NAME }}:${{ steps.date.outputs.date }}
          fiapmyburguer/${{ env.REPO_NAME }}:latest
  
